version: "3.9"
services:
  backend:
    build: ../backend
    env_file: ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
      - ../uploads:/app/uploads
  proxy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - backend
volumes:
  caddy-data:
  caddy-config:


